<?php
/** @var app\View $this */

use app\ConectJSON;
use app\IdGet;
use app\login;

$da = new ConectJSON();
$do = new IdGet();
$du = new login();

use app\auto;

$di = new auto();

$idu = $do->getDataId();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?= $tt ?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body>

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://primer/home">Home</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">


            <?php if (!$_SESSION["TOKEN"]) {
                echo '
                <form class="navbar-form navbar-right" action="http://primer/user/auth" method ="post">
                    <div class="form-group">
                        <input name="login" type="text" placeholder="login" class="form-control">
                    </div>
                    <div class="form-group">
                        <input name="password" type="password" placeholder="Password" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                </form>
             ';
            } else
                echo ' <form class="navbar-form navbar-right" action="http://primer/user/logout" method ="post">
                    <div class="form-group">' .
                    '<a class="class="form-control"" href="http://primer/user/show/"' . $_SESSION['id'] . '>' . $_SESSION['login'] . '</a>
                    </div>
                    
                    <button type="submit" class="btn btn-success">Logout</button>
                </form>'


            ?>
        </div><!--/.navbar-collapse -->
    </div>
</nav>

<div class="container">
    <?= $this->getContent();
    ?>


</div>
<footer class="footer">
    <p>&copy; <a href="http://primer/contacts"> 2018 Main Academy, Inc.</a></p>

</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="<?php echo PUBLIC_URL; ?>js/bootstrap.min.js"></script>
</body>
</html>
